config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  resources :books

  devise_for :users, controllers: { confirmations: 'confirmations' }

  get 'users/:id' => 'users#show', as: :user

  get 'purchases' => 'users#purchases', as: :user_purchases

  get 'book/:id/buy' => 'books#buy', as: :book_purchase

  root 'books#index'

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: [:show, :edit, :update, :destroy]

  # GET /purchases
  # GET /purchases.json
  def index
    @purchases = current_user.purchases.all
  end

  # GET /purchases/1
  # GET /purchases/1.json
  def show
  end

  # GET /purchases/new
  def new
    @purchase = current_user.purchases.new
  end

  # GET /purchases/1/edit
  def edit
  end

  # POST /purchases
  # POST /purchases.json
  def create
    @purchase = current_user.purchases.new(purchase_params)

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to @purchase, notice: 'A compra foi criada com sucesso.' }
        format.json { render :show, status: :created, location: @purchase }
      else
        format.html { render :new }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchases/1
  # PATCH/PUT /purchases/1.json
  def update
    respond_to do |format|
      if @purchase.update(purchase_params)

        #update the book state
        if @purchase.closed?
          @book = @purchase.book
          @book.sold = true
          @book.in_transaction = false
          @book.save
        end

        format.html { redirect_to @purchase, notice: 'A compra foi concluída com sucesso.' }
        format.json { render :show, status: :ok, location: @purchase }
      else
        format.html { render :edit }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1
  # DELETE /purchases/1.json
  def destroy

    #update the book state
    @book = @purchase.book
    @book.for_sale = true
    @book.sold = false
    @book.in_transaction = false
    @book.save

    @purchase.destroy
    respond_to do |format|
      format.html { redirect_to purchases_url, notice: 'A compra foi cancelada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase
      @purchase = current_user.purchases.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_params
      params.require(:purchase).permit(:book_id, :user_id, :closed)
    end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/_form.html.erb
<%= simple_form_for(@purchase) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :book, :readonly => true %>
    <%= f.input :user, :readonly => true %>


    <% if !@purchase.closed? %>
      <p><strong>Para concluir a compra, marque a caixa abaixo (Atenção: Após concluir a compra, a mesma não poderá mais ser modificada):</strong></p>
      <%= f.input :closed, :label => 'Compra concluída', as: :boolean %>
    <% end %>
  </div>

  <% if @purchase.closed? %>
    <h4>Esta compra está concluída e não pode mais ser modificada.</h4>
  <% else %>
    <div class="form-actions">
      <%= f.button :submit, :value => 'Atualizar' %>
    </div>
  <% end %>

<% end %>

app/views/purchases/edit.html.erb
<h1>Concluir Compra</h1>

<%= render 'form' %>

<hr>

<%= link_to 'Visualizar', @purchase %> |
<%= link_to 'Voltar', purchases_path %>

app/views/purchases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Minhas Compras</h1>

<table class="table">
  <thead>
    <tr>
      <th>Livro</th>
      <th>Comprador</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody class="table-striped">
    <% @purchases.each do |purchase| %>
      <tr>
        <td><%= purchase.book %></td>
        <td><%= purchase.user.profile.full_name %></td>
        <td><%= link_to_unless purchase.closed?, 'Cancelar', purchase, method: :delete, data: { confirm: 'Are you sure?' }%></td>
        <td><%= link_to_unless purchase.closed?, 'Concluir', edit_purchase_path(purchase) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/purchases/new.html.erb
<h1>New Purchase</h1>

<%= render 'form' %>

<%= link_to 'Back', purchases_path %>

app/views/purchases/show.html.erb
<h2> Compra  #<%= @purchase.id %></h2>

<p>
  <strong>Livro:</strong>
  <%= @purchase.book %>
</p>

<p>
  <strong>Vendedor:</strong>
  <%= @purchase.book.user.profile.full_name %>
</p>

<p>
  <strong>Comprador:</strong>
  <%= @purchase.user %>
</p>

<p>
  <strong>Concluída?:</strong>
  <% if @purchase.closed?  %>Sim<% else %>Não<% end %>
</p>

<%= link_to 'Editar', edit_purchase_path(@purchase) %> |
<%= link_to 'Voltar', purchases_path %>