config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  resources :books

  devise_for :users, controllers: { confirmations: 'confirmations' }

  get 'users/:id' => 'users#show', as: :user

  get 'purchases' => 'users#purchases', as: :user_purchases

  get 'book/:id/buy' => 'books#buy', as: :book_purchase

  root 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  belongs_to :purchase

  #must have a description
  validates :title, presence: true, length: { maximum: 120 }
  validates :user_id, presence: true

  #If more styles were added, don't forget to include a default image for that style
  #at app/assets/images/missing_STYLE.png. See also de config/initializers/paperclip.rb
  has_attached_file :image, :default_url => "book_:style.png", styles: {thumb: "160x213", medium: "250x333"}

  validates_attachment :image, presence: true,
                            content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
                            size: { less_than: 2.megabytes }

  def to_s
    self.title
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:edit, :update, :destroy]


  def buy
    @book = Book.find(params[:id])

    if @book
      @purchase = current_user.purchases.new
      @purchase.book_id = @book.id
      @purchase.save

      @book.in_transaction = true
      @book.purchase_id = @purchase.id

      respond_to do |format|
        if @book.save
          format.html { redirect_to @book, notice: 'Livro reservado com sucesso. Verifique seu e-mail para continuar a compra.' }
          format.json { render :show, status: :created, location: @book }
        else
          @purchase.destroy
          format.html { render :new }
          format.json { render json: @book.errors, status: :unprocessable_entity }
        end
      end
    else
       respond_to do |format|
        format.html { redirect_to @book, notice: 'Livro não encontrado!' }
       end
    end
  end

  # GET /books
  # GET /books.json
  def index
    @books = Book.order("created_at desc").page(params[:page]).per_page(12)
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])
  end

  # GET /books/new
  def new
    @book = current_user.books.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = current_user.books.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :year, :pages, :notes, :user_id, :image, :for_sale, :in_transaction, :sold)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div class="box<% if book.in_transaction? || book.sold? %> ribbon-container <% end %>" id="box-<%= book.id %>">

  <p class="box-title">
    <%= link_to book.title, book %>
  </p>

  <div class="box-cover">
    <%= image_tag book.image(:thumb)  %>
  </div>

  <p class="box-owner">
    Acervo de <%= link_to book.user.profile, book.user %>
  </p>

  <% if book.in_transaction? %>
    <span class="ribbon">Estou reservado :-)</span>
  <% elsif book.sold? %>
    <span class="ribbon">Fui vendido :-)</span>
  <% elsif book.for_sale? %>
    <div class="box-buttom">
      <%= link_to raw("<strong>R$ 10,00</strong> - QUERO LER ESTE"), book, :class => "btn btn-success btn-sm" %>
   </div>
  <% end %>

</div>

app/views/books/_buy.html.erb
<% if user_signed_in? && @book.user != current_user && (@book.for_sale? && !(@book.in_transaction? || @book.sold? )) %>
    <hr>

    <p class="big-box-notice--title">
      IMPORTANTE (Termos da Compra):
    </p>

    <p class="big-box-notice--text">
      Somente pessoas registradas no sistema podem efetuar compras e vendas. Ao clicar em comprar, o livro ficará reservado para você.
      Somente o vendedor pode liverar o livro novamente para venda, em caso de não conclusão da transação.
    </p>

    <p class="big-box-notice--text">
      Será enviado um e-mail a você com os dados do vendedor para  a conclusão da compra.
      <strong>Toda a transação (compra, envio) é de responsabilidade do comprador e vendedor, que deverão entrar em acordo a respeito da forma como a transação se realizará.</strong>
    </p>

    <p class="big-box-notice--text">
      Este site não tem responsabilidade sobre transações não concluídas ou qualquer produto anunciado,
      uma vez que serve apenas de plataforma de registro de acervos e meio de venda de livros.
      Este site destina-se apenas como meio de publicação e oferta de livros à venda por terceiros.
    </p>

    <p class="big-box-notice--text">
      Ao clicar em “Comprar”, você concorda com os termos e condições acima expostos e isenta o site e seu criador de qualquer responsabilidade sobre as transações efetuadas,
      assumindo a responsabilidade de negociação com o vendedor.
    </p>

    <div class="text-center">
      <%= link_to raw("<strong>COMPRAR</strong>"), book_purchase_path(@book), :class => "btn btn-lg btn-call--big" %>
    </div>
  <% else %>
    <% unless user_signed_in? %>
      <hr>

      <h2 class="text-center lead">PARA COMPRAR ESTE LIVRO VOCÊ PRECISA ESTAR REGISTRADO</h2>

      <div class="text-center">
        <%= link_to raw("<strong>QUERO ME REGISTRAR</strong>"), new_user_registration_path, :class => "btn btn-lg btn-call--big" %>  OU  <%= link_to raw("<strong>JÁ SOU REGISTRADO</strong>"), new_user_session_path, :class => "btn btn-lg btn-call--big" %>
      </div>
    <% end %>
  <% end %>

app/views/books/_form.html.erb
<%= simple_form_for(@book) do |f| %>
  <%= f.error_notification %>

  <%= image_tag @book.image(:thumb)  %>

  <div class="form-inputs">
    <%= f.full_error :image_file_size, class: "alert alert-error" %>
    <%= f.full_error :image_content_type, class: "alert alert-error" %>

    <%= f.input :image, label: "Carregar uma imagem de capa." %>

    <%= f.input :title, label: 'Título' %>
    <%= f.input :author, label: 'Autor' %>
    <%= f.input :year, label: 'Ano' %>
    <%= f.input :pages, label: 'Páginas' %>
    <%= f.input :notes, label: 'Observações', as: :text, input_html: { rows: "3" }  %>
    <%= f.input :for_sale, label: 'À venda', as: :boolean, disabled: @book.sold? || @book.in_transaction? %>
    <%= f.input :in_transaction, label: 'Em transação', as: :boolean, disabled: @book.for_sale? %>
    <%= f.input :sold, label: 'Vendido', as: :boolean, disabled: @book.sold? %>
  </div>

  <div class="actions">
    <%= f.submit 'Atualizar', class: "btn btn-lg btn-success btn-block" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4>Editar Livro</h4>
      </div>

      <div class="panel-body">

        <%= render 'form' %>

      </div>
    </div>

    <div class="big-box--backlink">
      <i class="fa fa-long-arrow-left"></i><%= link_to 'Voltar', @book %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<%= render 'pages/home' %>

<div id="books" class="box-container">
  <div class="row">
    <div class="col-md-12">
      <%= render @books %>
     </div>
  </div>
</div>

<div class="text-center">
  <%= will_paginate @books, renderer: BootstrapPagination::Rails %>
</div>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p class="big-box--owner">
  Acervo de <span><strong><%= @book.user.profile %><span></strong>
</p>

<div class="big-box">
  <div class="row">
    <div class="col-md-3">
      <div class="box-cover">
        <%= image_tag @book.image(:medium)  %>
         <!-- only the book's owner could edit and destroy -->
	      <% if current_user == @book.user %>
          <div class="big-box--toolbar">
            <% if !@book.sold? %>
              <%= link_to 'Editar', edit_book_path(@book), :class => "glyphicon glyphicon-pencil" %> |
              <%= link_to 'Excluir', @book, method: :delete, data: { confirm: 'Este livro será excluído do seu acervo. Tem certeza?' }, :class => "glyphicon glyphicon-erase" %>
            <% end %>
		      </div>
	      <% end %>
      </div>
    </div>
    <div class="col-md-9">

      <p class="big-box--title">
       <%= @book.title %>
      </p>
      <hr>

      <p>
        <strong>Autor:</strong>
        <%= @book.author %>
      </p>

     <p>
        <strong>Ano:</strong>
        <%= @book.year %>
      </p>

     <p>
       <strong>Páginas:</strong>
        <%= @book.pages %>
      </p>

      <p>
      <strong>Observações:</strong><br />
        <%= @book.notes %>
      </p>

      <% if @book.sold? && @book.user == current_user %>
          <hr>
          <P class="text-center">
          <strong>Este livro foi vendido. A única ação possível agora é <%= link_to 'ARQUIVAR', root_path %>.</strong><br />
          </P>
      <% end %>


    </div>

  </div>

  <%= render 'books/buy' %>

</div>

<div class="big-box--backlink">
  <i class="fa fa-long-arrow-left"></i><%= link_to 'Voltar', books_path %>
</div>