config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  resources :books

  devise_for :users, controllers: { confirmations: 'confirmations' }

  get 'users/:id' => 'users#show', as: :user

  get 'purchases' => 'users#purchases', as: :user_purchases

  get 'book/:id/buy' => 'books#buy', as: :book_purchase

  root 'books#index'

end

app/views/layouts/_footer.html.erb
<footer class="bs-footer" role="contentinfo">
  <div class="container">
    <div class="bs-social">
      <ul class="bs-social-buttons">
        <li class="follow-btn">
          <iframe id="twitter-widget-47" scrolling="no" frameborder="0" allowtransparency="true" src="https://platform.twitter.com/widgets/follow_button.403b2a3ca10837290e034c22c8a16c06.en.html#_=1435530003992&amp;dnt=false&amp;id=twitter-widget-47&amp;lang=en&amp;screen_name=jcfausto&amp;show_count=true&amp;show_screen_name=true&amp;size=m" class="twitter-follow-button twitter-follow-button" title="Twitter Follow Button" data-twttr-rendered="true" style="position: static; visibility: visible; width: 192px; height: 20px;"></iframe>
        </li>
        <li class="tweet-btn">
          <iframe id="twitter-widget-46" scrolling="no" frameborder="0" allowtransparency="true" src="https://platform.twitter.com/widgets/tweet_button.55a4019ea66c5d005a6e6d9d41c5e068.en.html#_=1435530003990&amp;count=horizontal&amp;dnt=false&amp;id=twitter-widget-46&amp;lang=en&amp;original_referer=http%3A%2F%2Frubyprimer.com%2Fepisodes%2Frails-assets&amp;related=jcfausto%3ACreator%20of%20RRubyPrime&amp;size=m&amp;text=Aprenda%20Ruby%20Através%20de%20Lições%20Rápidas%20%7C%20RubyPrimer%20-%20RubyPrimer&amp;url=http%3A%2F%2Frubyprimer.com%2F&amp;via=jcfausto" class="twitter-share-button twitter-tweet-button twitter-share-button twitter-count-horizontal" title="Twitter Tweet Button" data-twttr-rendered="true" style="position: static; visibility: visible; width: 81px; height: 20px;"></iframe>
        </li>
      </ul>
    </div>

    <p>
      <%= link_to "© 2015, Ler Mais Livros.", root_path, :target => "_blank" %>
    </p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-static-top" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Ler Mais Livros', root_path, class: "navbar-brand" %>
    </div>

    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Minhas compras", purchases_path %></li>
          <li><%= link_to "Novo livro", new_book_path %></li>
          <li><%= link_to "Perfil",  edit_user_registration_path %></li>
          <li><%= link_to 'Sair ('+current_user.email+')', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Registrar', new_user_registration_path %></li>
          <li><%= link_to 'Entrar', user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ler Mais Livros</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class="container">
    <%= render 'layouts/messages' %>

    <%= yield %>
  </div><!-- end container -->

  <%= render 'layouts/footer' %>

</body>
</html>